type Level = tuple[int, int] | None
type Trade = tuple[str, str, int, int]
type Tick = tuple[int, Level, Level, str]
type ReplayRow = tuple[int, int, int, int, str]
type SortRow = tuple[int, str, str, int | None, int]

class OrderBook:
    def __init__(self) -> None: ...
    def apply_order(self, order_id: str, side: int, price: int, volume: int) -> Trade | None: ...
    def cancel_order(self, order_id: str, volume: int | None = None) -> bool: ...
    def has_order(self, order_id: str) -> bool: ...
    def seed_level(self, side: int, price: int, volume: int, order_id: str) -> None: ...
    def reduce_level(self, side: int, price: int, volume: int) -> bool: ...
    def best_bid(self) -> Level: ...
    def best_ask(self) -> Level: ...
    def replay(self, background: list[ReplayRow], interventions: list[ReplayRow]) -> list[Tick]: ...

def sort_event_indices(rows: list[SortRow]) -> list[int]: ...
